### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by team3572** [mjansen4857/PathPlanner#1]
Forked the repo - was thinking of contributing this season.
But I cloned the repo, npm installed and tried to npm run build-mac and it fails with error.
It looks like a config file is missing maybe?
the failure looks like this...
```
> pathplanner@0.13.0 build-mac /Users/davisd/Documents/Projects/PathPlanner
> build --mac dir

/Users/davisd/Documents/Projects/PathPlanner/node_modules/read-config-file/out/main.js:71
async function readConfig(configFile, request) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at _readConfigFile (/Users/davisd/Documents/Projects/PathPlanner/node_modules/electron-builder/src/cli/cli.ts:10:1)
    at Object.args [as handler] (/Users/davisd/Documents/Projects/PathPlanner/node_modules/electron-builder/src/cli/cli.ts:45:5)
    at Object.runCommand (/Users/davisd/Documents/Projects/PathPlanner/node_modules/yargs/lib/command.js:238:44)
```

**Comment by team3572** [comment]
Thanks, upgrade did the trick. I was on a pretty old version on my development Mac.
