### ISSUE TITLE
File Selector not opening on Linux

### ISSUE THREAD

**Issue by person4268** [mjansen4857/pathplanner#148]
Hi, I just built the app from the latest git commit (6a19300a), and the file picker doesn't open, outputting this error in the console. 
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getDirectoryPath on channel plugins.flutter.io/file_selector)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294)
<asynchronous suspension>
#1      _WelcomePageState._showOpenProjectDialog (package:pathplanner/pages/welcome_page.dart:124)
<asynchronous suspension>
```
I'm running Arch Linux, and am using Flutter 3.3.8.

**Comment by person4268** [comment]
Updating file-selector from ^0.8.4 to ^0.9.0 in pubspec.yaml has fixed the issue, I'll try and make a PR.
