### ISSUE TITLE
Unable to launch v2023.4.2 on Mac

### ISSUE THREAD

**Issue by LTeixeira4909** [mjansen4857/pathplanner#360]
```
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ FileSystemException: Creation failed, path = '/deploy' (OS Error: Read-only file system, errno = 30)
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ #0   _Directory.createSync (dart:io/directory_impl.dart:129)
flutter: │ #1   _Directory.createSync (dart:io/directory_impl.dart:124)
flutter: │ #2   _HomePageState._loadPaths (package:pathplanner/pages/home_page.dart:532)
flutter: │ #3   _HomePageState.initState.<anonymous closure>.<anonymous closure> (package:pathplanner/pages/home_page.dart:112)
flutter: │ #4   State.setState (package:flutter/src/widgets/framework.dart:1133)
flutter: │ #5   _HomePageState.initState.<anonymous closure> (package:pathplanner/pages/home_page.dart:109)
flutter: │ #6   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ Dart Error
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by LTeixeira4909** [comment]
It seems to happen because I mistakenly choose a directory that is unwriteable. Now that directory seems to be cached somewhere

**Comment by mjansen4857** [comment]
`defaults delete com.mjansen4857.pathplanner` in terminal. Closing since this bug should be fixed in main branch.
